spring.application.name=springboot13
server.port=8090


spring.devtools.restart.enabled=true

# Propiedades asociadas al Actuator
management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.include=health,info,beans
management.endpoint.health.show-details=always

posibles valores: always, never, when-autorized 
management.endpoint.env.show-values=always

management.info.env.enabled=true
info.app.name=springboot11
info.app.version=1.0.0
info.app.description=Aplicación que demuestra el uso de las dependencias DevTools y Actuator

# Configuración de la base de datos PostgreSQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/laboratorio2
#spring.datasource.username=maxi
#spring.datasource.password=cuervo
#spring.datasource.driver-class-name=org.postgresql.Driver

 Configuración de la base de datos MySQL

spring.datasource.url=jdbc:mysql://localhost:3306/laboratorio
spring.datasource.username=springboot
spring.datasource.password=canzervero
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA Hibernate
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update    